name: Build and Release Ambient Music

env:
  main_project_module: app
  playstore_name: Ambient Music

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Decode and restore keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > release-keystore.jks
          ls -la release-keystore.jks
          pwd

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build APK Release - ${{ env.main_project_module }}
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          CI: true

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.main_project_module }}/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
