name: Build and Release Ambient Music

env:
  main_project_module: app
  playstore_name: Ambient Music

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install requests google-genai

      - name: Generate AI Changelog
        run: python generate_full_changelog.py --api-key "${{ secrets.GEMINI_API_KEY }}"

      - name: Read Changelog File
        id: read_changelog
        run: |
          {
            echo 'changelog_body<<EOF'
            cat changelog.txt
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Decode and restore keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > release-keystore.jks

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build APK Release
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          CI: true

      - name: Build AAB Release
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease
        env:
          SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          CI: true

      - name: Rename APK
        run: |
          apk_file=$(find ${{ env.main_project_module }}/build/outputs/apk/release -name "*.apk")
          mv "$apk_file" "Ambient-Music-${{ github.ref_name }}.apk"

      - name: Rename AAB
        id: find_aab
        run: |
          aab_file=$(find ${{ env.main_project_module }}/build/outputs/bundle/release -name "*.aab")
          mv "$aab_file" "Ambient-Music-${{ github.ref_name }}.aab"

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Ambient-Music-${{ github.ref_name }}.apk
            Ambient-Music-${{ github.ref_name }}.aab
          body: ${{ steps.read_changelog.outputs.changelog_body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
